type LiquidationEntity @entity(immutable: true) {
  id: ID!
  pool: Bytes!
  collateralAsset: Bytes!
  debtAsset: Bytes!
  user: Bytes!
  debtToCover: BigInt!
  liquidatedCollateralAmount: BigInt!
  liquidator: Bytes!
  receiveAToken: Boolean!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ACLRoleEntity @entity {
  id: ID!
  role: Bytes!
  roleName: String!
  account: Bytes!
  sender: Bytes!
  timestamp: BigInt!
  blockNumber: BigInt!
  transactionHash: Bytes!
  active: Boolean!
  pool: Bytes!
  poolAddressProvider: Bytes!
}
