type LiquidationEntity @entity(immutable: true) {
  id: ID!
  pool: Bytes!
  collateralAsset: Bytes!
  debtAsset: Bytes!
  user: Bytes!
  debtToCover: BigInt!
  liquidatedCollateralAmount: BigInt!
  collateralAssetPrice: BigInt!
  debtAssetPrice: BigInt!
  liquidator: Bytes!
  receiveAToken: Boolean!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ACLRoleEntity @entity {
  id: ID!
  role: Bytes!
  roleName: String!
  account: Bytes!
  sender: Bytes!
  timestamp: BigInt!
  blockNumber: BigInt!
  transactionHash: Bytes!
  active: Boolean!
  pool: Bytes!
  poolAddressProvider: Bytes!
}

type ReserveHistoryEntity @entity {
  id: ID!
  timestamp: BigInt!
  pool: Bytes!
  reserve: Bytes!
  totalSupply: BigInt!
  totalStableDebt: BigInt!
  totalVariableDebt: BigInt!
  totalDebt: BigInt!
  utilization: BigInt!
  liquidityRate: BigInt!
  stableBorrowRate: BigInt!
  variableBorrowRate: BigInt!
  liquidityIndex: BigInt!
  variableBorrowIndex: BigInt!
  lastUpdateTimestamp: BigInt!
}

type SnapshotState @entity {
  id: ID!
  lastSnapshotTimestamp: BigInt!
}
